Fix crash when removing a part from a drone
If a drone was busy repairing something, removing its repair part would
crash the game:

	Error: world/structureMath.lua:68: attempt to index local 'vectorB' (a nil value)
	stack traceback:
		[love "boot.lua"]:352: in function '__index'
		world/structureMath.lua:68: in function 'subtractVectors'
		world/shipparts/modules/drone.lua:225: in function 'getOrders'
		world/structure.lua:406: in function 'command'
		world/structure.lua:466: in function 'update'
		world/world.lua:231: in function 'update'
		gamestates/inGame.lua:308: in function 'update'
		main.lua:200: in function 'update'
		[love "callbacks.lua"]:162: in function <[love "callbacks.lua"]:144>
		[C]: in function 'xpcall'

This is because the drone didn't check whether it had a repair
capability or not. As long as it had a target for repair, it would try
to repair. Now it will only try to repair if it has a part with repair
capability.